#!/usr/bin/env bash
# bootstrap.sh — generates a GitHub token, sets up .ops toolkit, and installs Nix.
#
# Run once at session start:  bash bootstrap.sh
#
# Then in every subsequent bash command:
#   bash -c 'source /home/claude/.ghenv && <your command>'
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ── Source environment (resolves credentials from env vars) ──────────────────

. "${SCRIPT_DIR}/_env"

# ── Write private key to temp file (openssl dgst -sign requires a file) ──────

GITHUB_PRIVATE_KEY_FILE="$(mktemp)"
trap 'rm -f "$GITHUB_PRIVATE_KEY_FILE"' EXIT
# The key may have: literal \n escapes, surrounding double-quotes, or both.
# Strip outer quotes, then convert literal \n to real newlines.
_key="$GITHUB_PRIVATE_KEY"
_key="${_key#\"}"
_key="${_key%\"}"
printf '%b' "$_key" > "$GITHUB_PRIVATE_KEY_FILE"
chmod 600 "$GITHUB_PRIVATE_KEY_FILE"

# ── Generate JWT and exchange for installation token ─────────────────────────

NOW=$(date +%s)
_b64() { openssl base64 -e | tr -d '=\n' | tr '/+' '_-'; }
HDR=$(printf '{"alg":"RS256","typ":"JWT"}' | _b64)
PLD=$(printf '{"iat":%d,"exp":%d,"iss":"%s"}' $((NOW-60)) $((NOW+600)) "$GITHUB_APP_ID" | _b64)
SIG=$(printf '%s.%s' "$HDR" "$PLD" | openssl dgst -sha256 -sign "$GITHUB_PRIVATE_KEY_FILE" | _b64)

RESP=$(curl -sf -X POST \
  -H "Authorization: Bearer ${HDR}.${PLD}.${SIG}" \
  -H "Accept: application/vnd.github+json" \
  "https://api.github.com/app/installations/${GITHUB_INSTALLATION_ID}/access_tokens")

GITHUB_TOKEN=$(printf '%s' "$RESP" | python3 -c "import sys,json;print(json.load(sys.stdin)['token'])")

# ── Clone .ops toolkit (shallow — avoids pulling history of large nix snapshot)

git clone -q --depth 1 "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_ORG}/.ops.git" \
  /home/claude/.ops 2>/dev/null || true

# ── Install Nix from .ops snapshot ───────────────────────────────────────────

source /home/claude/.ops/lib/nix.sh
ensure_nix

# Capture the nix PATH so .ghenv can restore it without re-running ensure_nix
NIX_BIN_DIR="$(dirname "$(command -v nix)")"

# ── Write persistent env file for subsequent bash calls ──────────────────────

cat > /home/claude/.ghenv << EOF
# Auto-generated by bootstrap.sh — source this from bash, not sh.
if [ -z "\${BASH_VERSION:-}" ]; then
    echo "ERROR: .ghenv must be sourced from bash, not sh" >&2
    return 1 2>/dev/null || exit 1
fi

export GITHUB_TOKEN="${GITHUB_TOKEN}"
export GITHUB_ORG="${GITHUB_ORG}"
export PATH="${NIX_BIN_DIR}:\$PATH"

# Load .ops helper libraries (gh_get, gh_post, ensure_nix, etc.)
for f in /home/claude/.ops/lib/*.sh; do source "\$f" 2>/dev/null; done
EOF
chmod 600 /home/claude/.ghenv

# ── Write convenience wrapper ────────────────────────────────────────────────
# Allows: bash /home/claude/gh-run '<command>'

cat > /home/claude/gh-run << 'WRAPPER'
#!/usr/bin/env bash
source /home/claude/.ghenv
eval "$@"
WRAPPER
chmod +x /home/claude/gh-run

# ── Done ─────────────────────────────────────────────────────────────────────

echo "Ready — GitHub token, nix, and helpers are configured."
echo "  Use:  bash -c 'source /home/claude/.ghenv && <command>'"
echo "  Or:   bash /home/claude/gh-run '<command>'"
